import type { TestCatalog, TestSuite, TestCase } from '../../types';

/**
 * Markdown形式のフォーマッター
 */
export class MarkdownFormatter {
  /**
   * カタログをMarkdown文字列に変換
   */
  format(catalog: TestCatalog): string {
    let markdown = '';

    // ヘッダー
    markdown += this.generateHeader(catalog);

    // メタデータ
    markdown += this.generateMetadata(catalog);

    // テストスイート（Jest風の階層構造）
    markdown += this.generateTestSuitesHierarchy(catalog);

    // テスト数サマリー（describe毎）
    markdown += this.generateTestCountSummary(catalog);

    return markdown;
  }

  /**
   * ヘッダーを生成
   */
  private generateHeader(catalog: TestCatalog): string {
    return `# Test Catalog\n\n> Generated by Test Kanteen v${catalog.metadata.toolVersion}\n\n`;
  }

  /**
   * メタデータセクションを生成
   */
  private generateMetadata(catalog: TestCatalog): string {
    let md = '## Metadata\n\n';
    md += `- **Generated At**: ${catalog.metadata.generatedAt}\n`;
    md += `- **Source Files**: ${catalog.metadata.sourceFiles.length}\n`;
    md += `- **Test Suites**: ${catalog.testSuites.length}\n`;
    md += `- **Total Tests**: ${catalog.coverage.totalTests}\n\n`;
    return md;
  }


  /**
   * Jest風の階層構造でテストスイートを生成
   */
  private generateTestSuitesHierarchy(catalog: TestCatalog): string {
    let md = '## Test Suites\n\n';

    catalog.testSuites.forEach((suite) => {
      md += this.generateTestSuiteHierarchy(suite, 0);
    });

    return md;
  }

  /**
   * Jest風の階層構造で単一のテストスイートを生成
   */
  private generateTestSuiteHierarchy(suite: TestSuite, depth: number): string {
    let md = '';
    const indent = '  '.repeat(depth);

    // スイート名
    md += `${indent}${suite.name}\n`;

    // テストケース
    if (suite.tests && suite.tests.length > 0) {
      suite.tests.forEach((test) => {
        md += this.generateTestCaseHierarchy(test, depth + 1);
      });
    }

    // ネストされたスイート
    if (suite.nestedSuites && suite.nestedSuites.length > 0) {
      suite.nestedSuites.forEach((nested) => {
        md += this.generateTestSuiteHierarchy(nested, depth + 1);
      });
    }

    return md;
  }

  /**
   * Jest風の階層構造でテストケースを生成
   */
  private generateTestCaseHierarchy(test: TestCase, depth: number): string {
    const indent = '  '.repeat(depth);
    return `${indent}✓ ${test.name}\n`;
  }

  /**
   * describe毎のテスト数サマリーを生成
   */
  private generateTestCountSummary(catalog: TestCatalog): string {
    let md = '\n## Test Count by Describe\n\n';
    md += '| Describe | Test Count |\n';
    md += '|----------|------------|\n';

    const collectSuiteInfo = (suite: TestSuite, parentName = ''): Array<{name: string; count: number}> => {
      const fullName = parentName ? `${parentName} > ${suite.name}` : suite.name;
      const result: Array<{name: string; count: number}> = [];

      // 現在のsuiteのテスト数を追加（ネストされたsuiteのテストは含まない）
      if (suite.tests && suite.tests.length > 0) {
        result.push({ name: fullName, count: suite.tests.length });
      }

      // ネストされたsuiteを再帰的に処理
      if (suite.nestedSuites && suite.nestedSuites.length > 0) {
        suite.nestedSuites.forEach(nested => {
          result.push(...collectSuiteInfo(nested, fullName));
        });
      }

      return result;
    };

    const allSuites: Array<{name: string; count: number}> = [];
    catalog.testSuites.forEach(suite => {
      allSuites.push(...collectSuiteInfo(suite));
    });

    allSuites.forEach(suite => {
      md += `| ${suite.name} | ${suite.count} |\n`;
    });
    md += '\n';

    return md;
  }
}
