import type { TestCatalog, TestSuite, TestCase } from '../../types';

/**
 * Markdown形式のフォーマッター
 */
export class MarkdownFormatter {
  /**
   * カタログをMarkdown文字列に変換
   */
  format(catalog: TestCatalog): string {
    let markdown = '';

    // ヘッダー
    markdown += this.generateHeader(catalog);

    // メタデータ
    markdown += this.generateMetadata(catalog);

    // カバレッジ
    markdown += this.generateCoverage(catalog);

    // テストスイート（Jest風の階層構造）
    markdown += this.generateTestSuitesHierarchy(catalog);

    // 観点サマリー
    markdown += this.generateAspectsSummary(catalog);

    return markdown;
  }

  /**
   * ヘッダーを生成
   */
  private generateHeader(catalog: TestCatalog): string {
    return `# Test Catalog\n\n> Generated by Test Kanteen v${catalog.metadata.toolVersion}\n\n`;
  }

  /**
   * メタデータセクションを生成
   */
  private generateMetadata(catalog: TestCatalog): string {
    let md = '## Metadata\n\n';
    md += `- **Generated At**: ${catalog.metadata.generatedAt}\n`;
    md += `- **Framework**: ${catalog.metadata.framework}\n`;
    md += `- **Source Files**: ${catalog.metadata.sourceFiles.length}\n`;
    md += `- **Test Suites**: ${catalog.testSuites.length}\n`;
    md += `- **Total Tests**: ${catalog.coverage.totalTests}\n\n`;
    return md;
  }

  /**
   * カバレッジセクションを生成
   */
  private generateCoverage(catalog: TestCatalog): string {
    let md = '## Aspects Distribution\n\n';

    for (const [category, count] of Object.entries(catalog.coverage.aspectCategories)) {
      const percentage = ((count / catalog.coverage.totalTests) * 100).toFixed(1);
      md += `- **${category}**: ${count} tests (${percentage}%)\n`;
    }
    md += '\n';

    return md;
  }

  /**
   * Jest風の階層構造でテストスイートを生成
   */
  private generateTestSuitesHierarchy(catalog: TestCatalog): string {
    let md = '## Test Suites\n\n';

    catalog.testSuites.forEach((suite) => {
      md += this.generateTestSuiteHierarchy(suite, 0);
    });

    return md;
  }

  /**
   * Jest風の階層構造で単一のテストスイートを生成
   */
  private generateTestSuiteHierarchy(suite: TestSuite, depth: number): string {
    let md = '';
    const indent = '  '.repeat(depth);

    // スイート名
    md += `${indent}${suite.name}\n`;

    // テストケース
    if (suite.tests && suite.tests.length > 0) {
      suite.tests.forEach((test) => {
        md += this.generateTestCaseHierarchy(test, depth + 1);
      });
    }

    // ネストされたスイート
    if (suite.nestedSuites && suite.nestedSuites.length > 0) {
      suite.nestedSuites.forEach((nested) => {
        md += this.generateTestSuiteHierarchy(nested, depth + 1);
      });
    }

    return md;
  }

  /**
   * Jest風の階層構造でテストケースを生成
   */
  private generateTestCaseHierarchy(test: TestCase, depth: number): string {
    const indent = '  '.repeat(depth);
    return `${indent}✓ ${test.name}\n`;
  }

  /**
   * 観点サマリーを生成
   */
  private generateAspectsSummary(catalog: TestCatalog): string {
    let md = '\n## Test Aspects Summary\n\n';

    catalog.aspects.forEach((aspect) => {
      md += `### ${aspect.category}\n\n`;
      md += `${aspect.description}\n\n`;

      if (aspect.priority) {
        md += `**Priority**: ${aspect.priority.toUpperCase()}\n\n`;
      }

      md += `**Test Count**: ${aspect.testCases.length}\n\n`;

      if (aspect.examples && aspect.examples.length > 0) {
        md += '**Example Tests**:\n\n';
        aspect.examples.slice(0, 3).forEach((example) => {
          md += `- ${example}\n`;
        });
        md += '\n';
      }
    });

    return md;
  }
}
