import { BaseReporter } from '../base-reporter';
import type { TestCatalog, TestSuite, TestCase } from '../../types';

/**
 * Markdown形式でレポートを出力するReporter
 * Jest --verbose風のシンプルな階層構造
 */
export class MarkdownReporter extends BaseReporter {
  /**
   * Markdown形式のレポートを生成
   */
  generate(): string {
    const catalog = this.catalog as TestCatalog;
    let markdown = '';

    // ヘッダー
    markdown += '# Test Catalog\n\n';
    markdown += `> Generated by Test Kanteen v${catalog.metadata.toolVersion}\n\n`;

    // メタデータ
    if (this.options.include?.metadata && catalog.metadata) {
      markdown += '## Metadata\n\n';
      markdown += `- **Generated At**: ${catalog.metadata.generatedAt}\n`;
      markdown += `- **Framework**: ${catalog.metadata.framework}\n`;
      markdown += `- **Source Files**: ${catalog.metadata.sourceFiles?.length || 0}\n`;
      markdown += `- **Test Suites**: ${catalog.testSuites?.length || 0}\n`;
      markdown += `- **Total Tests**: ${catalog.coverage.totalTests}\n\n`;
    }

    // テストスイート（Jest風の階層構造）
    if (catalog.testSuites && catalog.testSuites.length > 0) {
      markdown += '## Test Suites\n\n';
      markdown += '```\n';
      catalog.testSuites.forEach((suite) => {
        markdown += this.generateSuiteHierarchy(suite, 0);
      });
      markdown += '```\n\n';
    }

    // テスト数サマリー（describe毎）
    if (catalog.testSuites && catalog.testSuites.length > 0) {
      markdown += this.generateTestCountSummary(catalog);
    }

    return markdown;
  }

  /**
   * Jest風の階層構造でスイートを生成
   */
  private generateSuiteHierarchy(suite: TestSuite, depth: number): string {
    let markdown = '';
    const indent = '  '.repeat(depth);

    // スイート名
    markdown += `${indent}${suite.name}\n`;

    // テストケース
    if (suite.tests && suite.tests.length > 0) {
      suite.tests.forEach((test) => {
        markdown += this.generateTestHierarchy(test, depth + 1);
      });
    }

    // ネストされたスイート
    if (suite.nestedSuites && suite.nestedSuites.length > 0) {
      suite.nestedSuites.forEach((nested) => {
        markdown += this.generateSuiteHierarchy(nested, depth + 1);
      });
    }

    return markdown;
  }

  /**
   * Jest風の階層構造でテストを生成
   */
  private generateTestHierarchy(test: TestCase, depth: number): string {
    const indent = '  '.repeat(depth);
    return `${indent}✓ ${test.name}\n`;
  }

  /**
   * describe毎のテスト数サマリーを生成
   */
  private generateTestCountSummary(catalog: TestCatalog): string {
    let md = '\n## Test Count by Describe\n\n';
    md += '| Describe | Test Count |\n';
    md += '|----------|------------|\n';

    const collectSuiteInfo = (suite: TestSuite, parentName = ''): Array<{name: string; count: number}> => {
      const fullName = parentName ? `${parentName} > ${suite.name}` : suite.name;
      const result: Array<{name: string; count: number}> = [];

      // 現在のsuiteのテスト数を追加（ネストされたsuiteのテストは含まない）
      if (suite.tests && suite.tests.length > 0) {
        result.push({ name: fullName, count: suite.tests.length });
      }

      // ネストされたsuiteを再帰的に処理
      if (suite.nestedSuites && suite.nestedSuites.length > 0) {
        suite.nestedSuites.forEach(nested => {
          result.push(...collectSuiteInfo(nested, fullName));
        });
      }

      return result;
    };

    const allSuites: Array<{name: string; count: number}> = [];
    catalog.testSuites.forEach(suite => {
      allSuites.push(...collectSuiteInfo(suite));
    });

    allSuites.forEach(suite => {
      md += `| ${suite.name} | ${suite.count} |\n`;
    });
    md += '\n';

    return md;
  }
}
