import { BaseReporter } from '../base-reporter';
import type { TestCatalog, TestSuite, TestCase } from '../../types';
import * as path from 'path';

/**
 * Markdown形式でレポートを出力するReporter
 * Jest --verbose風のシンプルな階層構造
 */
export class MarkdownReporter extends BaseReporter {
  /**
   * Markdown形式のレポートを生成
   */
  generate(): string {
    const catalog = this.catalog as TestCatalog;
    let markdown = '';

    // ヘッダー
    markdown += '# Test Catalog\n\n';
    markdown += `> Generated by Test Kanteen v${catalog.metadata.toolVersion}\n\n`;

    // メタデータ
    if (this.options.include?.metadata && catalog.metadata) {
      markdown += '## Metadata\n\n';
      markdown += `- **Generated At**: ${catalog.metadata.generatedAt}\n`;
      markdown += `- **Source Files**: ${catalog.metadata.sourceFiles?.length || 0}\n`;
      markdown += `- **Test Suites**: ${catalog.testSuites?.length || 0}\n`;
      markdown += `- **Total Tests**: ${catalog.coverage.totalTests}\n\n`;
    }

    // テストスイート（Jest風の階層構造）
    if (catalog.testSuites && catalog.testSuites.length > 0) {
      markdown += '## Test Suites\n\n';
      markdown += '```\n';
      catalog.testSuites.forEach((suite) => {
        markdown += this.generateSuiteHierarchy(suite, 0);
      });
      markdown += '```\n\n';
    }

    return markdown;
  }

  /**
   * Jest風の階層構造でスイートを生成
   */
  private generateSuiteHierarchy(suite: TestSuite, depth: number): string {
    let markdown = '';
    const indent = '  '.repeat(depth);

    // totalTests情報を追加
    const totalTestsInfo = suite.totalTests !== undefined ? ` (Total: ${suite.totalTests} tests)` : '';

    // スイート名（トップレベルのみファイルパスを表示）
    if (depth === 0 && suite.filePath) {
      // 相対パスに変換
      const relativePath = path.relative(process.cwd(), suite.filePath);
      markdown += `${indent}${suite.name} (${relativePath})${totalTestsInfo}\n`;
    } else {
      markdown += `${indent}${suite.name}${totalTestsInfo}\n`;
    }

    // テストケース
    if (suite.tests && suite.tests.length > 0) {
      suite.tests.forEach((test) => {
        markdown += this.generateTestHierarchy(test, depth + 1);
      });
    }

    // ネストされたスイート
    if (suite.nestedSuites && suite.nestedSuites.length > 0) {
      suite.nestedSuites.forEach((nested) => {
        markdown += this.generateSuiteHierarchy(nested, depth + 1);
      });
    }

    return markdown;
  }

  /**
   * Jest風の階層構造でテストを生成
   */
  private generateTestHierarchy(test: TestCase, depth: number): string {
    const indent = '  '.repeat(depth);
    return `${indent}✓ ${test.name}\n`;
  }
}
